# Generated by Django 2.0.6 on 2019-03-13 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RIEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='', max_length=1000)),
                ('createDate', models.DateField(default=datetime.datetime.now)),
                ('image', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WikiEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='', max_length=2000)),
                ('createdDate', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.CharField(default='', max_length=500)),
                ('WikiEntryFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WikiApp.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='rientrymodel',
            name='RIEntryFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WikiApp.WikiEntryModel'),
        ),
    ]
