# Generated by Django 2.0.6 on 2019-03-17 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WikiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikientrymodel',
            name='WikiEntryFK',
        ),
        migrations.AddField(
            model_name='wikientrymodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
