# Generated by Django 2.0.6 on 2019-03-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0003_auto_20190317_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.RenameField(
            model_name='rientrymodel',
            old_name='RIEntryFK',
            new_name='wiki',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
