# Generated by Django 2.0.6 on 2019-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0006_auto_20190317_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rientrymodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wikientrymodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
